[workspace]
members = ["plugins/cp2077-rs", "plugins/stupefied", "plugins/possessed", "plugins/addicted"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
cp2077-rs = { path = "./plugins/cp2077-rs" }
red4ext-rs = { git = "https://github.com/Roms1383/red4ext-rs.git", branch = "fork/pre-rework-ref-types", features = ["macros"] }
