[workspace]
members = ["plugins/cp2077-rs", "plugins/stupefied", "plugins/addicted"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.72"

[workspace.dependencies]
cp2077-rs = { path = "./plugins/cp2077-rs" }
red4ext-rs = { path = "../red4ext-rs/red4ext", features = ["macros"] }
