set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]
set dotenv-load
set fallback

mod      := 'Addicted'
source   := absolute_path(join('..', '..', 'scripts'))
tree     := join('r6', 'scripts')

@install TO:
    just dir '{{ join(TO, tree, mod) }}';
    just rcopy '{{ join(source, mod) }}' '{{ join(TO, tree, mod) }}'

@uninstall FROM:
    just trash '{{ join(FROM, tree, mod) }}'

@sweep:
    cd '{{source}}'; srgn --files 'Addicted/**/*.reds' --delete '\n?[[:space:]]*///* .+'
    cd '{{source}}'; srgn --files 'Addicted/**/*.reds' --delete '\n?[[:space:]]*(E|EI|F|FI)\(.+(?<=\);)'
    cd '{{source}}'; srgn --files 'Addicted/**/*.reds' --delete '\n?[[:space:]]*import Addicted\.Utils\..+'
